apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prostata-dependency 
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: observability 
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/dependency/prostata
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: postgres-ha-postgresql-ha-pgpool
      namespace: orthweb-prostata
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: orthweb-cert
      namespace: orthweb-prostata
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1 
      kind: HelmRelease
      name: istio-egress
      namespace: orthweb-prostata
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1 
      kind: HelmRelease
      name: istio-ingress
      namespace: orthweb-prostata
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: postgres-ha 
      namespace: orthweb-prostata
 
