site_name: Orthanc on Kubernetes
repo_name: digihunch/korthweb
repo_url: https://github.com/digihunch/korthweb
strict: true

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: 'index.md'
  - Infrastructure: 'infrastructure/index.md'
  - 'Platform Tooling': 'tooling/index.md'
  - Deployment:
    - 'Overview': 'deployment/overview.md'
    - 'GitOps Approach': 'deployment/gitops.md'
    - 'Helm Approach': 'deployment/helm.md'
    - 'Manual Approach': 'deployment/manual.md'
  - Validation: 
    - 'Overview': 'validation/overview.md'
    - 'GitOps Approach': 'validation/gitops.md'
    - 'Helm Approach': 'validation/helm.md'
    - 'Manual Approach': 'validation/manual.md'
  - Security: 'security/index.md'
  - Support: 'support/index.md'
plugins:
  - search
