apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egress
spec:
  releaseName: istio-egress 
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.16.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    name: istio-egressgateway
    service:
      type: ClusterIP 
    labels:
      app: istio-egressgateway
      istio: egressgateway
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
    nodeSelector:
      beta.kubernetes.io/os: linux
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
spec:
  releaseName: istio-ingress 
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.16.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    name: istio-ingressgateway
    service:
      type: LoadBalancer
      ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15020
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8443
      - name: dicom
        port: 11112
        protocol: TCP
        targetPort: 4242
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "suitable-porpoise-lb-subnet"
      # there is also an annotations attribute at service level but it is overwritten and not taking effect. this annotation attribute at root level is applied to all resources.
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
    nodeSelector:
      beta.kubernetes.io/os: linux
