apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mhr-orthweb
resources:
  - namespace.yaml
  - ../base/orthanc
  - ../base/route
transformers:
  - labels.yaml
images:
- name: orthanc-plugins
  # newName: imageserver.medtek.haukeland.no/orthanc-python-argo
  # newName: imageserver.medtek.haukeland.no/osimis-argo
  # newTag: 1.0.0
  newName: osimis/orthanc 
  digest: sha256:20413096878fb56bf8d09af08cf4055993dbcf507526f0561b26fc4d0ed7affc
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: orthanc-app
  data:
    db.addr: postgres-ha-postgresql-ha-pgpool.mhr-orthweb.svc.cluster.local 
replicas:
- name: orthanc
  count: 3
patches:
  - target:
      kind: Gateway
      name: dcm-gw
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts
        value:
        - www-233.medtek.haukeland.no
  - target:
      kind: Gateway
      name: web-gw
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts
        value:
        - www-233.medtek.haukeland.no
  - target:
      kind: VirtualService 
      name: dcm-vs
    patch: |-
      - op: replace
        path: /spec/hosts
        value:
        - www-233.medtek.haukeland.no
  - target:
      kind: VirtualService
      name: web-vs
    patch: |-
      - op: replace
        path: /spec/hosts
        value:
        - www-233.medtek.haukeland.no
  - target:
      kind: AuthorizationPolicy
      name: authz-policy-orthanc
    patch: |-
      - op: add
        path: /spec/rules/0/from/0/source/namespaces
        value:
        - istio-system
        - mhr-orthweb 
  - target:
      kind: AuthorizationPolicy
      name: authz-policy-orthanc 
    patch: |-
      - op: add
        path: /spec/rules/1/from/0/source/namespaces
        value: 
        - istio-system
        - mhr-orthweb
  - target:
      kind: AuthorizationPolicy
      name: authz-policy-postgres 
    patch: |-
      - op: add
        path: /spec/rules/0/from/0/source/namespaces
        value: 
        - mhr-orthweb
