apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: orthweb-tls-option
  namespace: {{ $.Release.Namespace | quote }}
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  clientAuth:
    clientAuthType: NoClientCert 
  sniStrict: false 
---
#apiVersion: traefik.containo.us/v1alpha1
#kind: TLSStore
#metadata:
#  name: dicom-tls-default
#  namespace: {{ $.Release.Namespace | quote }}
#spec:
#  certificates:
#    - secretName: {{ .Values.dcmtls.secretName | quote }}
#  defaultCertificate:
#    secretName: {{ .Values.dcmtls.secretName | quote }} 
#---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-ingressroute
  namespace: {{ $.Release.Namespace | quote }} 
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.https.certCommonName }}`)
      kind: Rule
      services:
        - name: orthweb-orthanc
          port: http
          strategy: RoundRobin
  tls:
    secretName: {{ .Values.https.secretName | quote }} 
    options:
      name: orthweb-tls-option
      namespace: {{ $.Release.Namespace | quote }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dicom-ingressroute
  namespace: {{ $.Release.Namespace | quote }}
spec:
  entryPoints:
    - dicomtls
  routes:
    - match: HostSNI(`{{ .Values.dcmtls.certCommonName }}`)
      services:
        - name: orthweb-orthanc
          port: dicom 
  tls:
    secretName: {{ .Values.dcmtls.secretName | quote }} 
    passthrough: false
    options:
      name: orthweb-tls-option
      namespace: {{ $.Release.Namespace | quote }}
    #store: 
    #  name: dicom-tls-default 
    #  namespace: {{ $.Release.Namespace | quote }}
