
{{- $ca := genCA .Values.catls.caCommonName 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.catls.secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $ca.Cert | b64enc | quote }}
  tls.key: {{ $ca.Key | b64enc | quote }}

{{- if .Values.dbtls }}
{{- $dbtlscert := genSignedCert .Values.dbtls.certCommonName nil (list .Values.dbtls.certCommonName) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbtls.secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $dbtlscert.Cert | b64enc | quote }}
  tls.key: {{ $dbtlscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}

{{- if .Values.dcmtls }}
{{- $dcmtlscert := genSignedCert .Values.dcmtls.certCommonName nil (list .Values.dcmtls.certCommonName) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dcmtls.secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $dcmtlscert.Cert | b64enc | quote }}
  tls.key: {{ $dcmtlscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}

{{- if .Values.https }}
{{- $httpscert := genSignedCert .Values.https.certCommonName nil (list .Values.https.certCommonName) 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.https.secretName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $httpscert.Cert | b64enc | quote }}
  tls.key: {{ $httpscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
