apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
apiVersion: v1
kind: Namespace
metadata:
  name: orthweb
  labels:
    istio-injection: enabled
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dbinit
  namespace: orthweb
data:
  db_create.sql: |
    CREATE DATABASE orthancdb;
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-app
  namespace: orthweb
data:
  orthanc.json: |
    {
      "Name" : "Orthanc Configuration",
      "RemoteAccessAllowed" : true,
      "SslEnabled" : false,
      "AuthenticationEnabled" : true,
      "RegisteredUsers" : {
        "admin" : "orthanc"
      },
      "DicomTlsEnabled" : false,
      "DicomTlsRemoteCertificateRequired" : false,
      "PostgreSQL" : {
        "EnableIndex" : true,
        "EnableStorage" : true,
        "Host" : "${DB_ADDR}",
        "Port" : 5432,
        "Database" : "orthancdb",
        "Username" : "${DB_USERNAME}",
        "Password" : "${DB_PASSWORD}",
        "EnableSsl" : false,
        "Lock" : false
      },
      "Plugins" : [
        "/usr/share/orthanc/plugins-available/libOrthancPostgreSQLIndex.so",
        "/usr/share/orthanc/plugins-available/libOrthancPostgreSQLStorage.so",
        "/usr/share/orthanc/plugins-available/libOrthancWebViewer.so"
      ]
    }
  db.engine: "postgres"
  db.port: "5432"
  db.addr: "postgres-ha-postgresql-ha-pgpool.orthweb.svc.cluster.local"
  db.user: postgres
