apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orthweb-cert
spec:
  commonName: medtek.haukeland.no
  secretName: orthweb-secret
  duration: 2160h
  renewBefore: 72h
  subject:
    organizations:
      - digihunch
  dnsNames:
    - www-231.medtek.haukeland.no
  privateKey:
    algorithm: RSA 
    size: 2048
  issuerRef:
    name: int-ca-issuer
    kind: Issuer
    group: cert-manager.io
