apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "1.11.0"
  interval: 5m0s
  test:
    enable: true
  install:
    remediation:
      retries: 3
      ignoreTestFailures: true #https://github.com/cert-manager/cert-manager/issues/2908
  values:
    installCRDs: true
