apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
spec:
  template:
    spec:
      containers:
      - name: orthanc
        env:
          - name: ORTHANC__NAME
            value: "Prostata Orthanc"

          # you must enable the StoneViewer and the DicomWeb plugins
          - name: STONE_WEB_VIEWER_PLUGIN_ENABLED
            value: "true"
          - name: DICOM_WEB_PLUGIN_ENABLED
            value: "true"

          - name: ORTHANC__DICOM_WEB__SERIES_METADATA
            value: "MainDicomTags"
          - name: ORTHANC__DICOM_WEB__STUDIES_METADATA
            value: "MainDicomTags"

          - name: ORTHANC__EXTRA_MAIN_DICOM_TAGS
            value:
              Instance:
                - Rows
                - Columns
                - ImageType
                - SOPClassUID
                - ContentDate
                - ContentTime
                - FrameOfReferenceUID
                - PixelSpacing
                - SpecificCharacterSet
                - BitsAllocated
                - BitsStored
                - RescaleSlope
                - RescaleIntercept
                - SliceThickness
                - WindowCenter
                - WindowWidth
                - PhotometricInterpretation
                - PixelRepresentation
              Series:
                - TimezoneOffsetFromUTC
                - PerformedProcedureStepStartDate
                - PerformedProcedureStepStartTime
                - RequestAttributesSequence
              Study:
                - TimezoneOffsetFromUTC
              Patient:

          # StoneViewer configurations
          - name: ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT
            value: "YYYY/MM/DD"

