apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
spec:
  template:
    spec:
      containers:
      - name: orthanc
        env:
          - name: ORTHANC__NAME
            value: "Prostata Orthanc"

          # you must enable the StoneViewer and the DicomWeb plugins
          - name: STONE_WEB_VIEWER_PLUGIN_ENABLED
            value: "true"
          - name: DICOM_WEB_PLUGIN_ENABLED
            value: "true"
          - name: OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED
            value: "true"
